**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
import numpy as np
arr = np.array([5, 15, 25, 35, 45])
print(arr)
zeros = np.zeros(7)
print(zeros)
ones = np.ones(6)
print(ones)
my_range = np.arange(10, 20)
print(my_range)

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [2]:
arr2 = np.array([12, 24, 36, 48, 60])
print(f"Помножені на 2: {arr2 * 2}")
print(f"Додано 10: {arr2 + 10}")
print(f"Піднесено до квадрату: {arr2 ** 2}")
print(f"Корінь: {np.sqrt(arr2)}")

Помножені на 2: [ 24  48  72  96 120]
Додано 10: [22 34 46 58 70]
Піднесено до квадрату: [ 144  576 1296 2304 3600]
Корінь: [3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [3]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(f"Середнє значення: {np.mean(data)}")
print(f"Мінімум: {np.min(data)}")
print(f"Максимум: {np.max(data)}")
print(f"Сумa всіх елементів: {np.sum(data)}")

Середнє значення: 45.42857142857143
Мінімум: 18
Максимум: 79
Сумa всіх елементів: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [4]:
arr3 = np.array([15, 22, 35, 44, 58, 67])
print(f"Перший елемент: {arr3[0]}")
print(f"Останній елемент: {arr3[-1]}")
print(f"Елементи з індексами 1 до 3: {arr3[1:4]}")
print(f"Елементи більші за 40: {arr3 [arr3 > 40]}")

Перший елемент: 15
Останній елемент: 67
Елементи з індексами 1 до 3: [22 35 44]
Елементи більші за 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [5]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [6]:
print(f"Форма матриці: {matrix.shape}")
print(f"Перший рядок: {matrix[0, :]}")
print(f"Друга колонка: {matrix[:, 1]}")
print(f"Сума всієї матриці: {np.sum(matrix)}")
print(f"Середнє всіх елементів: {np.mean(matrix)}")

Форма матриці: (3, 3)
Перший рядок: [2 4 6]
Друга колонка: [ 4 10 16]
Сума всієї матриці: 90
Середнє всіх елементів: 10.0
