### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
vector = np.random.rand(10)
matrix = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])
print(f'Вектор:\n{vector}')
print('Розмір вектору:', vector.shape)
print(f'Матриця:\n{matrix}')
print('Розмір матриці:', matrix.shape)

Вектор:
[0.66667407 0.20245347 0.80855353 0.67348224 0.34532519 0.341664
 0.669795   0.85369436 0.51987916 0.54841825]
Розмір вектору: (10,)
Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
v_plus = vector + 10
print(f'Додано 10: {v_plus.round(2)}')
matrix_mult = matrix * 2
print(f'Матриця помножена на 2:\n {matrix_mult.round(2)}')
v_square = np.square(vector)
print(f'Квадрат: {v_square.round(2)}')

Додано 10: [10.67 10.2  10.81 10.67 10.35 10.34 10.67 10.85 10.52 10.55]
Матриця помножена на 2:
 [[22 28 34]
 [40 46 52]
 [58 64 70]]
Квадрат: [0.44 0.04 0.65 0.45 0.12 0.12 0.45 0.73 0.27 0.3 ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [4]:
result_matrix = np.dot(A, B)
print(f'Помножені матриці А та В:\n{result_matrix}\n')
print("Shape result_matrix:", result_matrix.shape, "\nShape C:", C.shape)
print('Множення result_matrix @ C неможливе так як 3 != 2 (стовпці result × рядки C)')
print("\nShape D:", D.shape)
print("Множення result_matrix на D також неможливе з тієї ж причини")

Помножені матриці А та В:
[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]

Shape result_matrix: (3, 3) 
Shape C: (2, 1)
Множення result_matrix @ C неможливе так як 3 != 2 (стовпці result × рядки C)

Shape D: (2, 2)
Множення result_matrix на D також неможливе з тієї ж причини


In [5]:
print('Звичайне множення A × B дає 3×3, тому для множення на C (2×1) та D (2×2) використано транспонування обох матриць.')
print('Але математично рішення буде не вірним.\n')
result_matrix_2 = np.dot(A.T, B.T)
print(f'Помножені транспоновані матриці А та В:\n{result_matrix_2}\n')
result_с = np.dot(result_matrix_2, C)
print(f'Матриця помножена на вектор С:\n{result_с}\n')
result_в = np.dot(result_matrix_2, D)
print(f'Матриця помножена на матрицю D:\n{result_в}')

Звичайне множення A × B дає 3×3, тому для множення на C (2×1) та D (2×2) використано транспонування обох матриць.
Але математично рішення буде не вірним.

Помножені транспоновані матриці А та В:
[[0.7281 0.2034]
 [0.5202 0.2846]]

Матриця помножена на вектор С:
[[0.2034]
 [0.2846]]

Матриця помножена на матрицю D:
[[0.2034 0.7281]
 [0.2846 0.5202]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [6]:
result_matrix_t = result_matrix.T
print('Транспонована матриця:\n', result_matrix_t)
vector_t = vector.T
print('\nТранспонований вектор:\n', vector_t)
print('\nРозмір вектору:', vector_t.shape)
print('Змін у формі немає — плоский вектор транспонувати не можна')
column_vector = np.expand_dims(vector, axis=1)
print('\nДодано нову вісь:\n', column_vector)
print('\nРозмір вектору:', column_vector.shape)
print('Вектор після np.expand_dims — стовпцевий вектор:')
column_vector_t = column_vector.T
print('\nТранспонований вектор:\n', column_vector_t)
print('\nРозмір вектору:', column_vector_t.shape)
print('Тепер це рядковий вектор (1×10)')

Транспонована матриця:
 [[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]

Транспонований вектор:
 [0.66667407 0.20245347 0.80855353 0.67348224 0.34532519 0.341664
 0.669795   0.85369436 0.51987916 0.54841825]

Розмір вектору: (10,)
Змін у формі немає — плоский вектор транспонувати не можна

Додано нову вісь:
 [[0.66667407]
 [0.20245347]
 [0.80855353]
 [0.67348224]
 [0.34532519]
 [0.341664  ]
 [0.669795  ]
 [0.85369436]
 [0.51987916]
 [0.54841825]]

Розмір вектору: (10, 1)
Вектор після np.expand_dims — стовпцевий вектор:

Транспонований вектор:
 [[0.66667407 0.20245347 0.80855353 0.67348224 0.34532519 0.341664
  0.669795   0.85369436 0.51987916 0.54841825]]

Розмір вектору: (1, 10)
Тепер це рядковий вектор (1×10)
